DROP TABLE IF EXISTS SIMPLECALCULATOR;
CREATE TABLE SIMPLECALCULATOR (
  ID  VARCHAR(250) PRIMARY KEY,
  OPERATION VARCHAR(250) NOT NULL,
  FIRST_OPEARAND VARCHAR(250) NOT NULL,
  SECOND_OPERAND VARCHAR(250) NOT NULL,
  OPERATION_RESULT VARCHAR(250) NOT NULL
);